# Generated by Django 3.0.5 on 2020-04-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body',
            field=models.TextField(default='NOT_PROVIDED'),
        ),
    ]
